from .colors_config import Colors
from .htb_config import TOTAL_ACTIVE_MACHINES, TOTAL_ACTIVE_CHALLENGES, OWNERSHIP_DENOMINATOR
from .htb_utils import calculate_ownership_percentage, get_current_rank_by_percentage, get_next_rank_details